/*
 * DriveMode.cpp
 *
 *  Created on: Feb 14, 2015
 *      Author: robotics
 */

#include "DriveMode.h"

DriveMode::DriveMode(int EXTERNAL_CLAW_OPEN, int EXTERNAL_CLAW_CLOSED, int EXTERNAL_WINCH_UP, int EXTERNAL_WINCH_DOWN,
					int INTERNAL_ROLLER_IN, int INTERNAL_ROLLER_OUT, int INTERNAL_SOLENOID_ENGAGED, int INTERNAL_SOLENOID_DISENGAGED,
					int INTERNAL_DRIVE_UP, int INTERNAL_DRIVE_DOWN,
					func *MECANUM_FORWARDS, func *MECANUM_SIDEWAYS,  func *MECANUM_ROTATE)
{
	this->EXTERNAL_CLAW_OPEN = EXTERNAL_CLAW_OPEN;
	this->EXTERNAL_CLAW_CLOSED = EXTERNAL_CLAW_CLOSED;
	this->EXTERNAL_WINCH_UP = EXTERNAL_WINCH_UP;
	this->EXTERNAL_WINCH_DOWN = EXTERNAL_WINCH_DOWN;

	this->INTERNAL_ROLLER_IN = INTERNAL_ROLLER_IN;
	this->INTERNAL_ROLLER_OUT = INTERNAL_ROLLER_OUT;
	this->INTERNAL_SOLENOID_ENGAGED = INTERNAL_SOLENOID_ENGAGED;
	this->INTERNAL_SOLENOID_DISENGAGED = INTERNAL_SOLENOID_DISENGAGED;

	this->INTERNAL_DRIVE_UP = INTERNAL_DRIVE_UP;
	this->INTERNAL_DRIVE_DOWN = INTERNAL_DRIVE_DOWN;

	this->MECANUM_FORWARDS = *MECANUM_FORWARDS;
	this->MECANUM_SIDEWAYS = *MECANUM_SIDEWAYS;
	this->MECANUM_ROTATE = *MECANUM_ROTATE;

}

DriveMode::~DriveMode() {
	// TODO Auto-generated destructor stub
}

